---
apiVersion: l34.gateway.api.poc/v1alpha1
kind: L34Route
metadata:
  name: vip-20-0-0-1-port-4000
spec:
  parentRefs:
  - name: my-stateless-lb-gateway
  backendRefs:
  - name: service-b
    port: 4000 # This is ignored
  priority: 1
  destinationCIDRs:
  - 20.0.0.1/32
  - 40.0.0.1/32
  sourceCIDRs:
  - 0.0.0.0/0
  sourcePorts:
  - 0-65535
  destinationPorts:
  - "4000"
  protocols:
  - TCP