---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stateless-load-balancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stateless-load-balancer
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - l34.gateway.api.poc
  resources:
  - gatewayrouters
  - l34routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stateless-load-balancer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stateless-load-balancer
subjects:
- kind: ServiceAccount
  name: stateless-load-balancer
  namespace: default